defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3e1e7267-3a8d-4fb5-839b-f1ba5bc57b5d # Default
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  287f877d-f7ae-4cdd-a98b-2b5829b64a35: # CineCM
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
