defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1d6146b1-9013-4a36-8e18-220b4240560d # Page
handle: page
maxAuthors: 1
name: Page
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  287f877d-f7ae-4cdd-a98b-2b5829b64a35: # CineCM
    enabledByDefault: true
    hasUrls: true
    template: review/_entry.twig
    uriFormat: 'review/{slug}'
structure:
  maxLevels: null
  uid: 30754c63-5dce-4c86-a644-8da1286ef38b
type: structure
