defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 453b17d3-4b6e-48d2-bbe5-a3824c21a57d # Movie
handle: reviews
maxAuthors: 1
name: Reviews
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  287f877d-f7ae-4cdd-a98b-2b5829b64a35: # CineCM
    enabledByDefault: true
    hasUrls: true
    template: reviews/_entry.twig
    uriFormat: 'reviews/{slug}'
type: channel
