export const movies = [
    {  
        'background'    : '/images/movies/whiplash/background.jpg',
        'poster'        : '/images/movies/whiplash/poster.jpg',
        'directors'    : ['Damon Chazelle'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!', 
        'title'         : 'Whiplash',
        'year'         	: '2014',
        'type'         	: 'movie',
        'actors'        : ['Miles Teller', 'JK Simmons', 'Melissa Benoist'],
        'genres'        : ['Drama'],
        'rate'          : '92%',
        'url'          	: 'https://www.imdb.com/title/tt2582802/',
    },
    {  
        'background'    : '/images/movies/historyofviolence/background.jpg',
        'poster'        : '/images/movies/historyofviolence/poster.jpg',
        'directors'     : ['David Cronenberg'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'History Of Violence',
        'year'         	: '2005',
        'type'         	: 'tv',
        'actors'        : ['Viggo Mortensen', 'Maria Bello', 'Ed Harris'],
        'genres'        : ['Drama', 'Thriller'],
        'rate'          : '84%',
        'url'          	: 'https://www.imdb.com/title/tt0399146',
    },
    {  
        'background'    : '/images/movies/fightclub/background.jpg',
        'poster'        : '/images/movies/fightclub/poster.jpg',
        'directors'     : ['David Fincher'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'Fight Club',
        'year'         	: '1999',
        'type'         	: 'tv',
        'actors'        : ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
        'genres'        : ['Drama', 'Thriller', 'Action', 'Psychological'],
        'rate'          : '90%',
        'url'          	: 'https://www.imdb.com/title/tt0137523',
    },
    {  
        'background'    : '/images/movies/thething/background.jpg',
        'poster'        : '/images/movies/thething/poster.webp',
        'directors'     : ['John Carpenter'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'The Thing',
        'year'         	: '1982',
        'type'         	: 'movie',
        'actors'        : ['Kirk Russell', 'Keith David'],
        'genres'        : ['Horror', 'Thriller', 'Science-fiction'],
        'rate'          : '91%',
        'url'          	: 'https://www.imdb.com/title/tt0084787',
    },
    {  
        'background'    : '/images/movies/terminator2/background.jpg',
        'poster'        : '/images/movies/terminator2/poster.webp',
        'directors'     : ['James Cameron'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!', 
        'title'         : 'Terminator 2: Judgment Day',
        'year'         	: '1991',
        'type'         	: 'movie',
        'actors'        : ['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong', 'Robert Patrick'],
        'genres'        : ['Action', 'Science-fiction'],
        'rate'          : '95%',
        'url'          	: 'https://www.imdb.com/title/tt2582802/',
    },
    {  
        'background'    : '/images/movies/hereditary/background.webp',
        'poster'        : '/images/movies/hereditary/poster.webp',
        'directors'     : ['Ari Aster'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'Hereditary',
        'year'         	: '2018',
        'type'         	: 'movie',
        'actors'        : ['Toni Collette', 'Gabriel Byrne', 'Alex Wolff'],
        'genres'        : ['Horror', 'Thriller', 'Psychological'],
        'rate'          : '89%',
        'url'          	: 'https://www.imdb.com/title/tt0399146',
    },
    {  
        'background'    : '/images/movies/godfather/background.jpg',
        'poster'        : '/images/movies/godfather/poster.jpg',
        'directors'     : ['Francis Ford Coppolla'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'The Godfather',
        'year'         	: '1973',
        'type'         	: 'movie',
        'actors'        : ['Al Pacino', 'Marlon Brando', 'Robert Duvall', 'James Caan'],
        'genres'        : ['Drama', 'Mafia', 'Gangster'],
        'rate'          : '100%',
        'url'          	: 'https://www.imdb.com/title/tt0137523',
    },
    {  
        'background'    : '/images/movies/matrix/background.jpg',
        'poster'        : '/images/movies/matrix/poster.jpg',
        'directors'     : ['Lana Wachowski', 'Lilly Wachowski'],
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'The Matrix',
        'year'         	: '1999',
        'type'         	: 'movie',
        'actors'        : ['Keanu Reeves', 'Laurence Fishburne', 'Carie-Anne Moss', 'Hugo Weaving'],
        'genres'        : ['Science-fiction', 'Action'],
        'rate'          : '93%',
        'url'          	: 'https://www.imdb.com/title/tt0084787',
    },
];