export const movies = [
    {  
        'background'    : '/images/movies/whiplash/background.jpg',
        'poster'        : '/images/movies/whiplash/poster.jpg',
        'director'      : 'Damon Chazelle',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!', 
        'title'         : 'Whiplash',
        'year'         	: '2014',
        'type'         	: 'movie',
        'rate'          : '100%',
        'url'          	: 'https://www.imdb.com/title/tt2582802/',
    },
    {  
        'background'    : '/images/movies/historyofviolence/background.jpg',
        'poster'        : '/images/movies/historyofviolence/poster.jpg',
        'director'      : 'David Cronenberg',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'History Of Violence',
        'year'         	: '2005',
        'type'         	: 'tv',
        'rate'          : '88%',
        'url'          	: 'https://www.imdb.com/title/tt0399146',
    },
    {  
        'background'    : '/images/movies/fightclub/background.jpg',
        'poster'        : '/images/movies/fightclub/poster.jpg',
        'director'      : 'David Fincher',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'Fight Club',
        'year'         	: '1999',
        'type'         	: 'tv',
        'rate'          : '90%',
        'url'          	: 'https://www.imdb.com/title/tt0137523',
    },
    {  
        'background'    : '/images/movies/thething/background.jpg',
        'poster'        : '/images/movies/thething/poster.webp',
        'director'      : 'John Carpenter',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'The Thing',
        'year'         	: '1982',
        'type'         	: 'movie',
        'rate'          : '91%',
        'url'          	: 'https://www.imdb.com/title/tt0084787',
    },
    {  
        'background'    : '/images/movies/whiplash/background.jpg',
        'poster'        : '/images/movies/whiplash/poster.jpg',
        'director'      : 'Damon Chazelle',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!', 
        'title'         : 'Whiplash',
        'year'         	: '2014',
        'type'         	: 'movie',
        'rate'          : '100%',
        'url'          	: 'https://www.imdb.com/title/tt2582802/',
    },
    {  
        'background'    : '/images/movies/historyofviolence/background.jpg',
        'poster'        : '/images/movies/historyofviolence/poster.jpg',
        'director'      : 'David Cronenberg',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'History Of Violence',
        'year'         	: '2005',
        'type'         	: 'movie',
        'rate'          : '88%',
        'url'          	: 'https://www.imdb.com/title/tt0399146',
    },
    {  
        'background'    : '/images/movies/fightclub/background.jpg',
        'poster'        : '/images/movies/fightclub/poster.jpg',
        'director'      : 'David Fincher',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'Fight Club',
        'year'         	: '1999',
        'type'         	: 'movie',
        'rate'          : '90%',
        'url'          	: 'https://www.imdb.com/title/tt0137523',
    },
    {  
        'background'    : '/images/movies/thething/background.jpg',
        'poster'        : '/images/movies/thething/poster.webp',
        'director'      : 'John Carpenter',
        'description'   : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi adipisci dolor excepturi suscipit quidem, eveniet expedita explicabo ratione dicta ipsa!',
        'title'         : 'The Thing',
        'year'         	: '1982',
        'type'         	: 'movie',
        'rate'          : '91%',
        'url'          	: 'https://www.imdb.com/title/tt0084787',
    },
];