defaultPlacement: end
fieldLayouts:
  b5c6f32f-ba04-47f9-b3f4-72518ed9edfb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-29T03:09:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8a02fa71-42a5-4120-ad4d-afb5ccc34555
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75cb3939-e9a8-4389-a5b1-d63657cb8c9f
        userCondition: null
handle: actors
name: Actors
siteSettings:
  287f877d-f7ae-4cdd-a98b-2b5829b64a35: # CineCM
    hasUrls: true
    template: actors/_category.twig
    uriFormat: 'actors/{slug}'
structure:
  maxLevels: null
  uid: 3f762e09-1650-4a9c-9ed2-71ca1e98e9be
