defaultPlacement: end
fieldLayouts:
  a7010b21-ed7e-416e-9b14-50bf5e2de466:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-29T03:09:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 48e23142-e12e-481a-82ac-01ed4cce415f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15391617-1d1d-4be5-8ef4-1cd81d7c1c26
        userCondition: null
handle: directors
name: Directors
siteSettings:
  287f877d-f7ae-4cdd-a98b-2b5829b64a35: # CineCM
    hasUrls: true
    template: directors/_category.twig
    uriFormat: 'directors/{slug}'
structure:
  maxLevels: null
  uid: 69f6e08b-d097-46ca-92a2-f58d15552694
